### ISSUE TITLE
Diagram loses content when the editor is detached

### ISSUE THREAD

**Issue by ddimtirov** [Stefku/intellij-reference-diagram#47] opened 2015-12-12 04:03 UTC
1. Put the cursor on some method
2. Press `Ctrl+Alt+Shift+U` -> "Method reference Diagram"
3. Grab the tab of the newly opened diagram window and drag it outside of the main IntelliJ IDEA frame (say to your second monitor)

The dragged out window is empty and there is no obvious way to get the content back.

**Comment by Stefku** [comment] 2015-12-15 09:49
Currently, I've got not clue what the problem is. I keep on debugging and additionally ask for help in the forum: https://devnet.jetbrains.com/message/5566209

**Comment by Stefku** [comment] 2019-07-15 09:56
Just tried with current version and IntelliJ 2019.1.3 this problem does not occur any more. I close this bug.

**Closed by Stefku** 2019-07-15 09:56 UTC
Labels: bug, help wanted
